version: '3.9'

services:
  db:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ems-docker
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5430:5432"
    networks:
      - mynetwork
    depends_on:
      - db

volumes:
  postgres_data:

networks:
  mynetwork:
    driver: bridge
