version: '3.8'

services:
  db:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ems-docker
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5430:5432"
    networks:
      - mynetwork

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ems-mybatis-liquibase:latest
    container_name: ems-mybatis-liquibase
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/ems-docker
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - db
    ports:
      - "8082:8082"
    networks:
      - mynetwork

volumes:
  postgres_data:

networks:
  mynetwork:
    driver: bridge