package com.learning.emsmybatisliquibase.entity;

public enum JobTitleType {
    ENGINEER_TRAINEE,
    SOFTWARE_ENGINEER,
    SENIOR_SOFTWARE_ENGINEER,
    MODULE_LEAD,
    TECHNICAL_LEAD,
    PROJECT_LEAD,
    PROJECT_MANAGER,
    SENIOR_PROJECT_MANAGER,
    PRINCIPAL_DELIVERY_MANAGER,
    ASSOCIATIVE_DIRECTOR,
    SENIOR_DIRECTOR,
    CHIEF_DELIVERY_OFFICER,
    DEPUTY_CEO,
    CEO
}
